version: "3"
services:
  crypto-app:
    image: crypto-app
    build: ./Client/
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - cryptomedia
    volumes:
      - ./Client/src:/usr/src/app/src
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  crypto-server:
    image: crypto-server
    build: ./Server/
    ports:
       - "8000:8000"
    networks:
        - cryptomedia
    volumes:
        - ./Server:/usr/src/app
        - /usr/src/app/node_modules
    depends_on: 
        - mongo

  mongo:
    image: mongo:4.4-bionic
    ports: 
        - "27017:27017"
    networks:
        - cryptomedia
    volumes:
        - mongo-data:/data/db
  
networks:
    cryptomedia:
        driver: bridge

volumes:
    mongo-data:
        driver: local